name: Deploy React Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x  # remove quotes

      - name: Install deps & Build
        run: |
          npm install
          npm run build
        working-directory: .
        env:
          REACT_APP_API_URL: https://my-backend-app-fgftfxgtcshja7an.southindia-01.azurewebsites.net

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: my-frontend-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: ./frontend/build
